-- Nyíregyháza összes jelentős töltőállomása
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_01', 'Mobiliti', 'Tritium Veefil-RT 50kW', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_02', 'Mobiliti', 'Ensto Chalo 22kW', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_03', 'Mobiliti', 'Delta UFC 200', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_04', 'E.ON', 'ABB Terra 54', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_05', 'ALDI', 'Alfen Eve Double', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_06', 'ALDI', 'Alfen Eve Double', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_07', 'LIDL', 'Swarco SmartCharger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_08', 'LIDL', 'Swarco SmartCharger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_09', 'Penny', 'Etrel Inch', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_10', 'McDonald''s', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_11', 'ELMŰ', 'Efacec QC45', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_12', 'OMV', 'Ionity High Power Charger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_13', 'Shell', 'Shell Recharge DC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_14', 'MOL Plugee', 'ABB Terra 53', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_15', 'Hotel Pangea', 'Wallbe Pro', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_16', 'Nyíregyházi Egyetem', 'Mennekes Amtron', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_17', 'Korzó Bevásárlóközpont', 'Wallbe Eco', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_18', 'Bujtosi Szabadidő Csarnok', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_19', 'Vasútállomás', 'Siemens Sicharge', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_20', 'Sóstó Zoo', 'Alfen Eve Double', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_21', 'LEGO Factory', 'ABB Terra 24', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_22', 'Michelin Factory', 'ABB Terra 24', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_23', 'Stop Shop', 'Swarco SmartCharger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_24', 'Family Center', 'Swarco SmartCharger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_25', 'Auchan', 'Mobiliti 50kW DC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_26', 'Tesco Pazonyi út', 'Mobiliti 22kW AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_27', 'Tesco Tiszavasvári út', 'Mobiliti 22kW AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_28', 'Interspar', 'E.ON Drive', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_29', 'Jósa András Kórház', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_30', 'Múzeumfalu', 'Wallbe Pro', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_31', 'MOL Debreceni út', 'MOL Plugee 50kW', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_32', 'OMV Tiszavasvári út', 'OMV eMotion', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_33', 'Shell Sóstói út', 'Shell Recharge', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_34', 'Park Hotel', 'Mennekes Smart', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_35', 'Continental Arena', 'Etrel Inch', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_36', 'Városüzemeltetés', 'ABB Terra 54', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_37', 'KGRE Campus', 'Alfen Eve', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_38', 'Vay Ádám körút', 'ELMŰ AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_39', 'Országzászló tér', 'Mobiliti AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_40', 'Bujtosi-tó parkoló', 'TEA DC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_41', 'MOL Tokaji út', 'MOL Plugee 50kW', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_42', 'MOL 4-es főút', 'MOL Plugee 50kW', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_43', 'Penny Állomás tér', 'Etrel Inch', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_44', 'Penny Kállói út', 'Etrel Inch', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_45', 'ALDI Kállói út', 'Alfen Eve Double', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_46', 'LIDL Tiszavasvári út', 'Swarco SmartCharger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_47', 'McDonald''s Pazonyi út', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_48', 'Búza tér parkoló', 'Mobiliti AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_49', 'Hősök tere', 'Mobiliti AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_50', 'Nyír Plaza', 'E.ON Drive', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_51', 'Toyota Central', 'Menekkes Amtron', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_52', 'Volkswagen Szalon', 'ABB Terra 24', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_53', 'Hotel Aventinus', 'Wallbe Pro', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_54', 'Sóstó-Gyógyfürdő', 'Alfen Eve', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_55', 'LEGO Factory 2', 'ABB Terra 24', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_56', 'Michelin Factory 2', 'ABB Terra 24', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_57', 'Korzó P2 szint', 'Wallbe Eco', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_58', 'Állatpark Főbejárat', 'Alfen Eve Double', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_59', 'Múzeumfalu Parkoló', 'Wallbe Pro', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_60', 'Bujtosi Csarnok 2', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_61', 'ALDI Tiszavasvári út', 'Alfen Eve Double', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_62', 'LIDL Debreceni út', 'Swarco SmartCharger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_63', 'Penny Pazonyi út', 'Etrel Inch', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_64', 'OMV Debreceni út', 'OMV eMotion', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_65', 'Shell Tokaji út', 'Shell Recharge', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_66', 'Lukoil 4-es főút', 'ABB Terra 54', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_67', 'Megyeháza parkoló', 'Mobiliti AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_68', 'Polgármesteri Hivatal', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_69', 'Krúdy Vigadó Sóstó', 'Wallbe Pro', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_70', 'Városi Stadion', 'Alfen Eve', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_71', 'Nyíregyházi Főiskola B', 'Mennekes Amtron', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_72', 'LEGO Látogatóközpont', 'ABB Terra 24', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_73', 'Michelin Raktár', 'ABB Terra 24', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_74', 'Hübner Factory', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_75', 'Eissmann Factory', 'Wallbe Pro', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_76', 'Electrolux Factory', 'Alfen Eve Double', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_77', 'Master Good', 'ABB Terra 54', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_78', 'Diehl Aircabin', 'Mennekes Smart', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_79', 'Spar Korányi', 'E.ON Drive', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_80', 'Interspar László utca', 'E.ON Drive', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_81', 'Tesco Expressz Sóstó', 'Mobiliti AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_82', 'ALDI Korányi', 'Alfen Eve Double', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_83', 'LIDL Orosi út', 'Swarco SmartCharger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_84', 'MOL Orosi út', 'MOL Plugee 50kW', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_85', 'OMV Korányi', 'OMV eMotion', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_86', 'Shell László utca', 'Shell Recharge', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_87', 'McDonald''s Debreceni út', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_88', 'Burger King Pazonyi út', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_89', 'KFC Stop Shop', 'Wallbe Eco', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_90', 'Praktiker parkoló', 'TEA DC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_91', 'Media Markt', 'Swarco SmartCharger', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_92', 'Mömax parkoló', 'Alfen Eve', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_93', 'Jysk Pazonyi út', 'Wallbe Pro', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_94', 'Euronics Family Center', 'Etrel Inch', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_95', 'Kormányablak Hatzel tér', 'Mobiliti AC', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_96', 'Jósa András Múzeum', 'Schneider EVlink', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_97', 'Móricz Zsigmond Színház', 'Wallbe Eco', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_98', 'Váci Mihály Központ', 'Alfen Eve', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_99', 'Sóstói Kilátó', 'Wallbe Pro', 'OFFLINE', NOW());
INSERT INTO charge_points (id, vendor, model, status, created_at) VALUES ('CP_NYIREGYHAZA_100', 'Aquarius Élményfürdő', 'Alfen Eve Double', 'OFFLINE', NOW());
